from pydoc import text
from tkinter import * 
root = Tk()
menu = Menu(root)
root.config(menu=menu)
filemenu = Menu(menu)
menu.add_cascade(label='File', menu=filemenu)
filemenu.add_command(label='New')
filemenu.add_command(label='Open')
filemenu.add_command(label='Save')
filemenu.add_separator()
filemenu.add_command(label='Exit', command=root.quit)
helpmenu = Menu(menu)
menu.add_cascade(label='Help', menu=helpmenu)
helpmenu.add_command(label='About') 
w = Label(root, text="Hello, World!")
w.pack()
var1 = IntVar()
Checkbutton(root, text='male', variable=var1).pack()
var2 = IntVar()
Checkbutton(root, text='female', variable=var2).pack()
v = IntVar()
Radiobutton(root, text='one', variable=v, value=1).pack(anchor=W)
Radiobutton(root, text='two', variable=v, value=2).pack(anchor=W)
Radiobutton(root, text='three', variable=v, value=3).pack(anchor=W)
Lb = Listbox(root)
Lb.insert(1, 'one')
Lb.insert(2, 'two')
Lb.insert(3, 'three')
Lb.insert(4, 'four')
Lb.pack()
scrollbar = Scrollbar(root)
scrollbar.pack(side=RIGHT, fill=Y)
mylist = Listbox(root, yscrollcommand=scrollbar.set)
for line in range(100):
    mylist.insert(END, "This is line number " + str(line))
mylist.pack(side=LEFT, fill=BOTH, expand=True)
scrollbar.config(command=mylist.yview)
w = Scale(root, from_=0, to=42)
w.pack()
w = Scale(root, from_=0, to=200, orient=HORIZONTAL)
w.pack()
root.mainloop()
